package de.kirill.activityrecord.api;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.JdbcTypeCode;

import java.time.LocalDate;
import java.time.LocalTime;

import static jakarta.persistence.GenerationType.AUTO;
import static org.hibernate.type.SqlTypes.*;

/** Entity class representing an activity record. */
@Entity
@Table(name = "activity_record")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class ActivityRecord {
    /** Unique identifier for the activity record. Generated by the database. */
    @Id
    @GeneratedValue(strategy = AUTO)
    @Column(nullable = false)
    @JdbcTypeCode(BIGINT)
    private Long id;

    /** Name of the employee associated with the activity. */
    @Column(name = "employee_name")
    private String employeeName;

    /** Project name associated with the activity. */
    @Column(name = "project")
    private String project;

    /** Date when the activity was recorded. */
    @Column(name = "date_of_proof")
    @JdbcTypeCode(DATE)
    private LocalDate dateOfProof;

    /** Location where the activity took place. */
    @Column(name = "location")
    private String location;

    /** Work package associated with the activity. */
    @Column(name = "work_package")
    private String workPackage;

    /** Description of the activity. */
    @Column(name = "description")
    private String description;

    /** Workload time for the activity. */
    @Column(name = "workload")
    @JdbcTypeCode(TIME)
    private LocalTime workload;

    /** Indicates if the activity is billable to the customer. */
    @Column(name = "customer_billable")
    @JdbcTypeCode(BOOLEAN)
    private Boolean customerBillable = false;
}
